### ISSUE TITLE
Is it possible to attach multiple pty to spawned process?

### ISSUE THREAD

**Issue by cravler** [Tyriar/node-pty#101]
I need ability to spawn process and attach to it multiple pty, so that every pty can specify their size (cols, rows)

**Comment by Tyriar** [comment]
Not possible currently. I think it is doable though as I believe the [resize](https://github.com/Tyriar/node-pty/blob/bf6b6b0647f819cf85c7e939a68ccfb6c2e03a14/src/unix/pty.cc#L394) call only applies to the master size of the pty. It's out of the scope of this project though.
