### ISSUE TITLE
Property 'on' does not exist on type 'ITerminal'

### ISSUE THREAD

**Issue by rollandjb** [Tyriar/node-pty#105]
I tried putting the code below adapted form the fork example in a typescript file. I get a compiler error:

`Property 'on' does not exist on type 'ITerminal'`

I wanted to try this out in a node app. I notice that `on` is declared on the `Terminal` class in `lib/terminal.d.ts`. Is there some Typescript configuration I need to make this work?

```
import * as pty from 'node-pty'

const term = pty.spawn('bash', [], {
    name: 'xterm-color',
    cols: 80,
    rows: 30,
    cwd: process.env.HOME,
    // env: process.env || {}
});

term.on('data', function (data) {
    console.log(data);
});

term.write('ls\r');
term.resize(100, 40);
term.write('ls\r');

setTimeout(term.kill.bind(term), 5000);
```

**Comment by Tyriar** [comment]
There may be issues with the linking of the typings as I haven't tested it thoroughly. Are you getting the error from running `tsc`?

To unblock yourself you can workaround it by casting `term` to an `<any>`

**Comment by rollandjb** [comment]
Yes the error manifests when running `tsc` and in vs code.

`tsconfig`  is 

```
{
  "compilerOptions": {
    "target": "ES2015", 
    "module": "commonjs",
    "sourceMap": true,
    "outDir": "./dist",
    "strict": true,
    "moduleResolution": "node"
  }
}
```

and `package.json` is

```
{
  "name": "asyncawait",
  "version": "1.0.0",
  "description": "",
  "main": "dist/index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "node-pty": "^0.6.8"
  },
  "devDependencies": {
    "@types/node": "^8.0.9",
    "typescript": "^2.4.1"
  }
}
```

**Comment by Tyriar** [comment]
Thanks for the report, it's fixed. Will publish soon 😃

**Comment by Tyriar** [comment]
0.6.9 should look like this:

<img width="678" alt="screen shot 2017-07-09 at 5 14 19 pm" src="https://user-images.githubusercontent.com/2193314/27998836-180db508-64ca-11e7-8779-4cca18812d45.png">

**Comment by rollandjb** [comment]
It's a pleasure! Thanks for the quick response.
