### ISSUE TITLE
Automate dependency installation for Windows

### ISSUE THREAD

**Issue by stevenvachon** [Tyriar/node-pty#111]
Because https://github.com/Tyriar/node-pty/issues/109 is annoying.

You could use [windows-build-tools](https://npmjs.com/windows-build-tools) as inspiration.

**Comment by Tyriar** [comment]
https://www.npmjs.com/package/windows-build-tools would increase build/download time significantly, there's a similar issue opened atm that would solve the same problem: https://github.com/Tyriar/node-pty/issues/46
