### ISSUE TITLE
Get the pid on event

### ISSUE THREAD

**Issue by japita-se** [Tyriar/node-pty#125]
When this event is fired
```
term.on("data",function(data){
});
```

is it possible to get the pid of the terminal which fired the data?
Regards

**Comment by Tyriar** [comment]
No it's not possible to get the PID of the nested process that gives the data as that's all encapsulated within the shell. You can get the shell PID via `term.pid` however, which you can use to get the child process tree.

**Comment by japita-se** [comment]
So is not possible to know which shell emitted the data?
Regards

**Comment by Tyriar** [comment]
You can get the PID of the top-level process you created only. For example, if you launch bash via node-pty and then run some executable in bash, node-pty knows nothing about what's happening inside bash.

**Comment by japita-se** [comment]
Can we talk in private? My email is
demarco DOT giu AT gmail DOT com
