### ISSUE TITLE
PTY output break command into multiple lines

### ISSUE THREAD

**Issue by zhaoyi0113** [Tyriar/node-pty#130]
I am using `node-pty` on Mac. Below is the source code:

```
let pty = require('node-pty');
const stripAnsi = require('strip-ansi');
let ptyProcess = pty.spawn('bash', [], {
  name: 'xterm-color',
  cols: 80,
  rows: 30,
  cwd: process.env.HOME,
  env: process.env
});

ptyProcess.on('data', function(data) {
  const o = stripAnsi(data);

  console.log(o);
});
ptyProcess.on('exit', function(data) {
  console.log('exit', data);
});
setTimeout(() => {
  ptyProcess.write('db.getSiblingDB("admin").runCommand( { getParameter : "*" })');
}, 2000);
```

after running this code, I get below output:

```
$ node nodepty.js
bash-3.2$
db.getSibling
DB("admin").runCommand( { getParameter : "*" })
```

it looks like the input command `db.getSiblingDB("admin").runCommand( { getParameter : "*" })` is broken into mutiple lines.. How to solve this issue? I would expect the output should be:
```
bash-3.2$ db.getSiblingDB("admin").runCommand( { getParameter : "*" })
```

**Comment by Tyriar** [comment]
The output comes through not in full lines. It's actually `console.log` adding the new line to the output. Try adding `o` to a buffer string and remove/print lines from it when `'\n` is hit.

**Comment by zhaoyi0113** [comment]
I see what you mean. I can use `process.stdout.write(o);` to print the output. But I found that the callback function is called three times while I only write one line command. Is there any buffer I can set to make it to be called one time?

**Comment by Tyriar** [comment]
You'll need to write your own buffer to do that (it could just be a string):

```js
var buffer = '';
ptyProcess.on('data', function(data) {
  buffer += stripAnsi(data);
  printFullLinesFromBuffer(buffer);
});

function printFullLinesFromBuffer() {
  while (buffer.indexOf('\n') !== -1) {
    var i = buffer.indexOf('\n');
    // Pull complete line
    var newLine = buffer.substr(0, i);
    console.log(newLine);
    // Remove complete line from buffer
    buffer = buffer.substr(i + 1);
  }
}
```

Remember that this will keep the last line in the buffer though until a trailing `\n` is hit. You could also use `process.stdout.write(o)` while is like console.log without the added new line.

```js
ptyProcess.on('data', function(data) {
  process.stdout.write(stripAnsi(data));
```
