### ISSUE TITLE
Get duplicate line output on mac

### ISSUE THREAD

**Issue by zhaoyi0113** [Tyriar/node-pty#131]
I use below code running on mac os. 

```
let pty = require('node-pty');
const stripAnsi = require('strip-ansi');
let ptyProcess = pty.spawn('mongo', [], {
  name: 'xterm-color',
  cols: 80,
  rows: 30,
  cwd: process.env.HOME,
  env: process.env
});

ptyProcess.on('data', function(data) {
  const o = stripAnsi(data);
  process.stdout.write(o);
});
ptyProcess.on('exit', function(data) {
  console.log('exit', data);
});
setTimeout(() => {
  ptyProcess.write('db\r');
}, 1000);
```

It just launch a `mongo` client and write a `db` command to through pty. The output is:

```
> dbdb
test
>
```

You can see that the command `db` is duplicated in the output. I have tested all other commands and all of them are duplicated. Is there any reason for that? Why the output becomes duplicate?

**Comment by Tyriar** [comment]
I don't have mongo installed, Can you come up with a repro case without mongo?

**Comment by cooltoo** [comment]
I couldn't reproduce it by other command. But when I debug the callback function, I see this value on the `data` parameter:

"> db[3G[Jdb[5G"

The weird thing I found is that if I use `StringDecoder` like below:
```
const { StringDecoder } = require('string_decoder');
const decoder = new StringDecoder('utf8');
```
then change the callback function:
```
ptyProcess.on('data', function(data) {
  const o = decoder.write(data);
  process.stdout.write(o);
});
```

I can get the correct output from console. But when I debug the code I still see the duplicate string on debug console output. So I would say there is something character converting happens on the terminal window. Not sure why this happens.

**Comment by Tyriar** [comment]
It's happening because you're stripping the ANSI escape sequences instead of using them:

```
> db�[3G�[Jdb�[5G
```

Means:

```
"> db"   -> Print "> db"
"�[3G"  -> Go to the 3rd column (d)
"�[J"   -> Erase below
"db"     -> Print "db"
"�[5G"  -> Move cursor to 5th column (after db)
```

This is as expected, you can't just strip the escape sequences as rewriting lines or portions of lines is a common occurrence.

**Comment by zhaoyi0113** [comment]
Thanks for pointing out this. 
Do you have any idea on what the correct way to translate the ANSI?

**Comment by Tyriar** [comment]
Write a terminal emulator 😄 eg. https://github.com/sourcelair/xterm.js

There may be easier ways to do it in a console window using node/npm libs but I'm not sure which ones.
