### ISSUE TITLE
Windows git bash returns weird output

### ISSUE THREAD

**Issue by cjhoward92** [Tyriar/node-pty#137]
Hey all, I am trying to use this with gitbash on windows 10. Works great other than the fast that the output is really weird, and it comes with a lot of weird characters. I am wondering if there is an example of some environment variables that will allow me to get normal looking output or if this is an issue with bash on windows?

Some example output:

```
hello world[0K[?25l
exit[0K[?25h[?25l
[0K[?25h
```

That is from running this shell script

```
#!/bin/sh

echo hello world
exit 1
```

I am spawning like so

```javascript
const runner = pty.spawn('C:\\Program Files (x86)\\Git\\usr\\bin\\sh.exe', [], { cwd, env });
runner.write('C:\\\\Dev\\\\hooks\\\\.git\\\\hooks\\\\pre-commit  0<&- && exit || exit');
runner.write('\n');
```

Let me know if you need anymore info from me. Not sure what else you would want to see. I do not have any `TERM` environment variable but I tried setting it to `xterm` and `xterm-256color` and nothing changed.

Thanks!

**Comment by cjhoward92** [comment]
After researching this a little later, it looks like these are probably the ansi color codes from the terminal. Is there a way to disable them?

**Comment by rprichard** [comment]
Strictly speaking, these aren't color escapes, but they *are* ANSI escapes:

 * 0K ==> erase rest of line
 * ?25l ==> hide cursor
 * ?25h ==> show cursor

On Windows, node-pty uses winpty, which has a flag [WINPTY_FLAG_PLAIN_OUTPUT](https://github.com/rprichard/winpty/blob/ce9239af5d751195ea6982a41c7d71356ac9201c/src/include/winpty_constants.h#L59) that suppresses ANSI escapes.  winpty ordinarily generates ANSI escapes even for programs that only write unescaped text.

**Comment by cjhoward92** [comment]
Cool, thanks! Is there a way I can set that flag from the node-pty package?

**Comment by jrop** [comment]
@cjhoward92 One thing you could do is try passing the output to something like [strip-ansi](https://www.npmjs.com/package/strip-ansi).

**Comment by cjhoward92** [comment]
@jrop I will try that for now, thanks!

**Comment by jerch** [comment]
@cjhoward92 Your question is somewhat weird, are you sure that you need a pty at all? The pty thing is intended to be run with a terminal emulator, that would deal with those characters. Maybe a simple child process will do? If not (since some processes rely on it), maybe a simpler abstraction like a pexpect implementation will do? It does all those low level stuff for you...

**Comment by cjhoward92** [comment]
Hey @jerch, I'll explain to you what we have going on and maybe you can offer some insight. We are trying to run some commands that operate on the terminal in Mac, Windows, and Linux. These commands often time prompt for credentials. We found that using `child_process.spawn` does not properly return `stdout` when these prompts occur, leaving us in a frozen state (Our app is an electron app) since we don't get any output. We ended up using `node-pty` because it does properly output prompts from the terminal, so we can listen for them and output our response with `<theptyprocess>.write`. it seemed to solve the problem, mostly, in a really roundabout way. It's not ideal, as I would like to use spawn, but it works well enough.

The frozen output issue was a particular sticking point on Ubuntu 16.04.

If you have heard of anything like this and know of a cleaner solution, let me know.

We have it implemented on Windows this way so we don't have to rewrite anything substantial across OS boundaries.

**Comment by Tyriar** [comment]
Can you provide the credentials as arguments with child_process.spawn?

**Comment by cjhoward92** [comment]
No. We have no way of knowing if credentials will be required or what they would be.

**Comment by Tyriar** [comment]
Then I think your 2 choices are stripping ansi escapes as per https://github.com/Tyriar/node-pty/issues/137#issuecomment-324660972, parsing them yourself (this is quite complicated), or use a lib like [xterm.js](https://github.com/sourcelair/xterm.js) to handle that for you and run the process IO through that.

**Comment by cjhoward92** [comment]
Thanks for all the help. I agree, those are our choices. BTW node-pty works great so thanks for getting up and running so smoothly on windows!

**Comment by Tyriar** [comment]
Great!

I just realized I put 3 choices, not 2 😛

**Comment by jerch** [comment]
![5 beer](https://image.spreadshirtmedia.com/image-server/v1/mp/products/P15613671T174A1MPC21066523PA259PT14/views/1,width=800,height=800,appearanceId=1,backgroundColor=E8E8E8,version=1440496893/kelly-green-sawmill-long-sleeve-shirts-men-s-long-sleeve-t-shirt-by-next-level.jpg)
Sorry for the big image...
