### ISSUE TITLE
spawn is sending exit before all data is received

### ISSUE THREAD

**Issue by twifty** [Tyriar/node-pty#140]
This is happening about 1 out of every 5 times. I've set up the instance as:

```js
this.pty = spawn(args[0], args.slice(1), {
    cols: this.terminal.cols,
    rows: this.terminal.rows,
    cwd: cwd,
    env: env,
    name: 'xterm-color',
});

this.pty.on('data', data => {
    console.log(data)
    this.terminal.write(data);
});

this.pty.on('error', data => {
    console.log(`error ${data}`)
    this.terminal.write(data);
});

this.pty.on('exit', (code, signal) => {
    console.log(`exiting with ${code} ${signal}`)
    this.pty.destroy();
    this.pty = null;
});
```
the command I'm running is `php /var/www/work/bin/console list` (which is a symfony project). Quite randomly the output is cut short, at seemingly random offsets. Though, but not always, I have noticed the last received data buffer has a 4095 length.

I'm running this within the Atom editor v1.19 on a Manjaro linux system.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Tyriar/node-pty/issues/72
