### ISSUE TITLE
Utilities for handling updating winpty DLLs

### ISSUE THREAD

**Issue by amejia1** [Tyriar/node-pty#141]
On Windows, DLLs which are currently loaded by a process cannot be deleted. To update them, the old DLLs need to be moved somewhere on the same volume and marked for deletion on system restart (see https://msdn.microsoft.com/en-us/library/windows/desktop/ms682604(v=vs.85).aspx).

I have an Atom package which utilizes node-pty named atom-xterm. Every time the atom-xterm package needs to be updated, I have to take care to rename the winpty DLLs through a 'preinstall' and 'preuninstall' script of my own (see https://github.com/amejia1/atom-xterm/blob/master/scripts/move-winpty-binaries.js). The script I own never marks them for deletion on restart.

Though Atom package updates are handled differently than how npm handles them, it would still be nice if node-pty provided a special utility script for dealing with updating the winpty DLLs which I can then utilize in the atom-xterm package.

**Comment by Tyriar** [comment]
No plans to add anything to the core lib as it's so specific to Atom's update mechanism (I don't really want to own that code). It looks like the script you have is working out fine for you though?
