### ISSUE TITLE
A dynamic link library (DLL) initialization routine failed error on node webkit

### ISSUE THREAD

**Issue by saianugraha100** [Tyriar/node-pty#144]
Hello,

I am using node-pty on my project. It is a node-webkit based application. It is working fine in mac.

On the windows, it throws the following error on the require statement
'A dynamic link library (DLL) initialization routine failed'. 

Demo application of xterm.js works fine in windows.It looks like an issue only on nw.

I tried the suggestion from the following link and didn't help
http://docs.nwjs.io/en/latest/For%20Users/Advanced/Use%20Native%20Node%20Modules/

Any suggestion will be appreciated

Thanks
Ram

**Comment by saianugraha100** [comment]
I got it resolved by executing the following steps

1. install nw-gyp 'npm install nw-gyp -g' 
2. Edit C:\Users\xxx\AppData\Roaming\npm\node_modules\nw-gyp\src\win_delay_load_hook.cc
3. Replace the content from the following link https://github.com/nwjs/nw.js/blob/nw25/tools/win_delay_load_hook.cc
   25 is the major version of the nw used.
4. 'cd node-pty' and then execute 'nw-gyp rebuild --target=0.25.2 --arch=x64'

Thanks
Ram

**Comment by SunXinFei** [comment]
nw-gyp is still error, 
node-gyp is ok.
