### ISSUE TITLE
Is it possible to preserve colors from the nested tty? 

### ISSUE THREAD

**Issue by mateodelnorte** [Tyriar/node-pty#145]
I'd like to preserve colors from the child command, when used in a situation like the fork.js example. 

Is this possible?

**Comment by Tyriar** [comment]
It should work just fine, here's me launching bash inside bash inside bash:

![kapture 2017-09-29 at 16 36 24](https://user-images.githubusercontent.com/2193314/31035000-5f5869d0-a534-11e7-9ab0-8ab78a8c5e98.gif)

Is that what you mean?

**Comment by mateodelnorte** [comment]
<img width="281" alt="screen shot 2017-09-29 at 4 40 32 pm" src="https://user-images.githubusercontent.com/554847/31035157-f7809e8a-a534-11e7-89a6-0289e75b7fdd.png">

Yup. 100%. Just modified the example and checked it out locally. Awesome. Thx.

**Comment by Tyriar** [comment]
Great 😄
