### ISSUE TITLE
winpty.exe seen as threat by Norton

### ISSUE THREAD

**Issue by Gum-Joe** [Tyriar/node-pty#147]
A few days ago  I was using Hyper Terminal when a message popped up from my Norton about SONAR protection and how the build of `winpty.exe` was behaving strangely.

From Norton clipboard printout of the 'threat':
```
Filename: winpty-agent.exe
Threat name: SONAR.AM.C.P!g12

Few Users
Hundreds of users in the Norton Community have used this file.

New
This file was released 13 days ago.

High
This file risk is high.

Source: External Media

Source File:
update.exe

File Created:
winpty-agent.exe
File Actions (username hidden and replaced with pc)

File: d:\users\pc\appdata\local\hyper\app-1.4.7\resources\app.asar.unpacked\node_modules\node-pty\build\release\ winpty-agent.exe Threat Removed
File: d:\Users\pc\AppData\Local\microsoft\CLR_v4.0\usagelogs\ powershell.exe.log Threat Removed
File: d:\Users\pc\AppData\Local\microsoft\Windows\powershell\ startupprofiledata-interactive Threat Removed
File: d:\Users\pc\AppData\Local\microsoft\Windows\powershell\ moduleanalysiscache Threat Removed
```
Is there a reason for this?  I would like to think it is because of the exe not being signed, though the fact Norton reports (though I highly doubt this) that PowerShell files were infected doesn't look like something leaving an app unsigned would cause.

Thanks in advance.

**Comment by Tyriar** [comment]
I haven't seen this before and both VS Code and Hyper have been on node-pty for a long time. I believe we do sign winpty-agent.exe for VS Code, maybe Hyper doing the same is the fix?

**Comment by Gum-Joe** [comment]
@Tyriar Hyper says they sign the exe.  Probably just (as I expected) Norton just being, well, Norton

**Comment by Tyriar** [comment]
Yeah I guess it's just Norton being overly aggressive then, winpty does do some pretty low level things to accomplish what it needs to do.

**Comment by Gum-Joe** [comment]
What about powershell? Just another safe guard

**Comment by Tyriar** [comment]
I don't know what's going on there, I would guess this is all Norton's fault. It complained about a .log file 😕
