### ISSUE TITLE
odd behaviour when trying to copy text inside of vim

### ISSUE THREAD

**Issue by ricktbaker** [Tyriar/node-pty#148]
I'm using a combination of electron, xterm.js and node-pty on a mac.   Normal copying works fine if I cat a file out, or just try and copy some terminal text.   But when I try and copy some text while using vi, it copies something completely different, like the underlying text, or maybe something even in the past buffer.

I'm trying to figure out exactly what's going on, but figured I'd bring it up here in case anyone has seen anything similar.

EDIT: Ok, it's definitely copying from the buffer.   If I start a terminal, fire up vim, copy the first line inside the vim editor, it actually copies the very first line from my terminal session.

Seems to be the case with any curses based application.   If I run 'top' I get the same behavior.

EDIT: This could be an issue with xterm.js and not node-pty.   I'm trying to debug that to get more information.

**Comment by mofux** [comment]
@ricktbaker I think it is an issue with xterm.js. Can you figure out which version of xterm.js you are running?

**Comment by ricktbaker** [comment]
@mofux xterm@2.9.2

**Comment by mofux** [comment]
Could you create an issue on the xterm repo, then I'll try to reproduce it tomorrow. Looks like the text is always copied from the normal buffer, even if the alt buffer is active...

**Comment by ricktbaker** [comment]
Certainly.   I appreciate you looking into.   I'll close out the issue here to prevent confusion.
