### ISSUE TITLE
1% is not a valid Win32 application

### ISSUE THREAD

**Issue by JackieLs** [Tyriar/node-pty#150]
I install the node-pty pkg on mac. And I packaged it in the electron.exe. Then I use it in windows.
Something Error Like: `1% is not a valid Win32 application`
So why this happened?

**Comment by Tyriar** [comment]
You probably build it using your on system version of node, not Electron's version of node. See the Electron example for how to do this: https://github.com/Tyriar/node-pty/blob/master/examples/electron/npm_install.sh

**Comment by JackieLs** [comment]
@Tyriar Thx.I've read the example of Electron.And the problem is solved.

**Comment by Jandou6** [comment]
I try to use the `npm_install.sh` but, the question can not resolve. @JackieLs  Can you give me more information about this question. Help me how to solve.
