### ISSUE TITLE
Expose native on the node-pty module again so that xterm.js can upgrade

### ISSUE THREAD

**Issue by Tyriar** [Tyriar/node-pty#153]
Tests within xterm.js rely on `.native` from node-pty v0.4, as a temporary workaround so that xterm.js can move forward I want to expose `.native` again but not as a public API.

https://github.com/sourcelair/xterm.js/blob/8ece306dbe9c7aee13cce9c60fae74202f8660ee/src/Terminal.integration.ts#L86

@jerch I think some of your finer-grained APIs in https://github.com/Tyriar/node-pty/issues/73 will let us remove the dependency on native. If so we should consider pulling those particular APIs in first 😃

**Comment by jerch** [comment]
@Tyriar Well the `RawPty` could be used instead, it is kinda a wrapper around all low level pty stuff on unix.
