### ISSUE TITLE
on close event

### ISSUE THREAD

**Issue by tasoss** [Tyriar/node-pty#161]
Hello.
Is it possible on the "close" event to know the exit code or the signal used?

**Comment by Tyriar** [comment]
You should listen to `exit`, not close https://github.com/Tyriar/node-pty/blob/97b3ca171a05e01491150a553dc4f31c0d74203c/src/unixTerminal.ts#L98

It gives the code and signal on Linux/macOS, on Windows it will only give the exit code as signals aren't a thing on Windows https://github.com/Tyriar/node-pty/blob/97b3ca171a05e01491150a553dc4f31c0d74203c/src/windowsTerminal.ts#L110
