### ISSUE TITLE
[Question] Set path after initialization?

### ISSUE THREAD

**Issue by davej** [Tyriar/node-pty#177]
I am trying to add a path to the `PATH` env, doing something like this:

```js
this.ptyProcess = pty.spawn(this.shell, [], {
  name: "xterm-color",
  cols: this.term.cols,
  rows: this.term.rows,
  cwd: directory,
  env: {
    ...process.env,
    PATH: `/some/path/:${process.env.PATH}`
  }
});
```

But it doesn't always work because some `.bash_rc` (or similar) files are setting a new `PATH` env var explicitly. The current workaround that I'm using is to do this:

```js
this.ptyProcess.write(`export PATH=/some/path/:${process.env.PATH}\r`);
```

Is there a better way to do this? The solution above works but it prints unwanted output to the terminal. I'm looking for a solution that won't output to the terminal if possible.

I've come up with this (below) but it's super hacky. Basically I won't start writing `ptyProcess` data to the terminal until I see some arbitrary unicode symbol. 

```js
let shouldWriteToTerm = false
this.ptyProcess.on("data", data => {
  if (data.includes("🎉")) shouldWriteToTerm = true
  if (!shouldWriteToTerm) {
    // Don't write to term if we haven't seen the special character
    return;
  }
  this.term.write(data);
});

this.ptyProcess.write(`export PATH=/some/path/:${process.env.PATH}\r`);
this.ptyProcess.write(`echo 🎉\r`);
```

This is unpredictable though because sometimes the lines are repeated twice before they are actually executed:

![image](https://user-images.githubusercontent.com/26971/36049235-f656bb4e-0dd9-11e8-9db0-b63bf6ad81fb.png)

Is there a way to wait until the `ptyProcess` is ready to accept input so that input won't be repeated?

**Comment by Tyriar** [comment]
I think launching `bash --noprofile --norc` is probably the better way to do this, if avoiding those scripts is an option. If not then the best you can do is what you're doing then clearing the prompt after init.

**Comment by davej** [comment]
Thanks!

**Comment by davej** [comment]
The answer is probably 'no' but is there a way to wait until bash/shell is ready to accept input so that input won't be repeated? Perhaps there is a character sequence that I can expect?

**Comment by Tyriar** [comment]
Not that I'm aware of unfortunately
