### ISSUE TITLE
write to process without echo-ing the message

### ISSUE THREAD

**Issue by dusadrian** [Tyriar/node-pty#180]
Hello, newbye here.
Would it be possible to send a message (command) to a process, but without displaying that command in the terminal (such as xterm.js)?

Ideally, it should also receive a response.

It should not be `write` (which echoes in the terminal), but presumably something else. Something in the direction of:
`console.log(ptyProcess.write('ls\r'));`

(thus receiving the result in the Javascript caller)
Thanks in advance.

**Comment by Tyriar** [comment]
Other than something like [this](https://unix.stackexchange.com/a/28620/115410), the only way to do something like this is to intercept the data stream and remove characters from it before it gets to your terminal.

**Comment by dusadrian** [comment]
Thanks a lot. Will look for a way to intercept the data stream then. A simple example would help a lot (I am a total newbie), but this helps as well.
