### ISSUE TITLE
Make the location of `pty.node` configurable

### ISSUE THREAD

**Issue by derekbekoe** [Tyriar/node-pty#181]
Is it possible not make the location of `pty.node` configurable in https://github.com/Tyriar/node-pty/blob/master/src/unixTerminal.ts#L21?

I am packaging xterm.js using [pkg](https://github.com/zeit/pkg) and have to modify `unixTerminal.ts` in my `node_modules` to point to `pty.node` being in a different location.

This is my current workaround:
```
var pty = process.pkg ? require(path.join(path.dirname(process.execPath), 'pty.node')) : require(path.join('..', 'build', 'Release', 'pty.node'));
```

**Comment by Tyriar** [comment]
@derekbekoe why is this necessary? Does pkg move things around or something?

**Comment by derekbekoe** [comment]
`pkg` does not handle `*.node` files yet.
https://github.com/zeit/pkg#native-addons
So I have to include it separately and modify the path to it.

This is not blocking me as I can just make that change in node_modules when I delete my `node_modules` but at this point, I'm just calling it out.

**Comment by Tyriar** [comment]
It seems like a problem with pkg to me as this is one of the [standard directories](https://github.com/TooTallNate/node-bindings/blob/58141c6ce00b2f7690d7115e6635fdd5739b7fd0/bindings.js#L19-L35) that the .node is built to. I'd say use the workaround for now, maybe pkg will have a general solution eventually?

**Comment by derekbekoe** [comment]
Okay that's fine
