### ISSUE TITLE
Unicode support on packaged Electron app

### ISSUE THREAD

**Issue by davej** [Tyriar/node-pty#191]
This is probably more of a support question than an issue so apologies but I'm not finding any answers elsewhere.

---

I'm using node-pty with an electron app. In development mode when launching from the command-line everything works as expected. However when I package the app up into a `.app` file for production then unicode characters no longer work. E.g.. `í` appears as `I??`.

If I open the packaged app from the command line then it will work correctly. The issue only occurs when launching the application directly from the app icon. My first thought was that the `env` config wasn't being inherited correctly but I've checked and both versions of the app have the exact same `env` keys and values passed into `node-pty`.

I'm hoping somebody might have some idea of what might be causing this and how to fix it.

**Comment by Tyriar** [comment]
> My first thought was that the env config wasn't being inherited correctly but I've checked and both versions of the app have the exact same env keys and values passed into node-pty.

@davej on macOS the environment differs when you launch via the terminal and the dock. So your statement doesn't match what I've observed. Specifically `.bashrc`/`.bash_profile` may not be run as expected when you're running via the dock.

**Comment by davej** [comment]
No luck I'm afraid. Thanks for your help anyway. 👍
