### ISSUE TITLE
Progress bars and spinners sometimes get printed across multiple lines

### ISSUE THREAD

**Issue by Tyriar** [Tyriar/node-pty#2]
It happens inconsistently, not on every update.

![image](https://cloud.githubusercontent.com/assets/2193314/20072724/5c576ae4-a4de-11e6-8d14-d84e9c729610.png)

**Comment by s-a** [comment]
If you resize console window during runtime this is normal behavior on Windows.

**Comment by Tyriar** [comment]
Yeah I think there may not be a way around this, I'll double check by confirming what winpty sees in the background before closing off.

**Comment by Tyriar** [comment]
I think this may be fixed now after the latest winpty was adopted in 0.6. It's an upstream issue regardless.
