### ISSUE TITLE
Interactive shell demo

### ISSUE THREAD

**Issue by s-a** [Tyriar/node-pty#27]
Hello Tyriar,
I try to figure out how to handle user interactive shell commands within node.js.

I tried:

In cmd.exe
```bash
touch test1.js
touch test2.js
copy test1.js test2.js
test2.js überschreiben? (Ja/Nein/Alle): n
        0 Datei(en) kopiert.
```

With node-pty
```javascript
var os = require('os');
var pty = require('node-pty');

var shell = os.platform() === 'win32' ? 'powershell.exe' : 'bash';

var ptyProcess = pty.spawn(shell, [], {
  name: 'xterm-color',
  cols: 80,
  rows: 30,
  cwd: process.env.HOME,
  env: process.env
});

ptyProcess.on('data', function(data) {
  console.log(data);
});

ptyProcess.write('copy test1.js test2.js\r'); 
```

Which does not output ~~anything~~ interactive shell text and user input. Can you point me to the right direction?

**Comment by Tyriar** [comment]
Does running `node ./demos/fork_demo.js` as is output anything?

**Comment by s-a** [comment]
Yes, but when it comes to interactive shell mode it does not output text I input via keyboard. When I press enter it executes command I entered. So it buffers keys from input correct, but 
```javascript
ptyProcess.on('data', function(data) {
  console.log(data);
});
```

does not trigger. 

```bash
node -v
v7.3.0
ver
Microsoft Windows [Version 10.0.10586]
```

```bash
C:\git\node-pty\node-pty\demo>node fork_demo.js

Windows PowerShell
Copyright (C) 2015 Microsoft Corporation. Alle Rechte vorbehalten.


PS C:\git\node-pty\node-pty\demo>
PS C:\git\node-pty\node-pty\demo> ls




    Verzeichnis: C:\git\node-pty\node-pty\demo


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       18.01.2017     19:13            452 fork_demo.js
-a----       18.01.2017     19:13            574 open_demo.js



PS C:\git\node-pty\node-pty\demo> ls


    Verzeichnis: C:\git\node-pty\node-pty\demo


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       18.01.2017     19:13            452 fork_demo.js
-a----       18.01.2017     19:13            574 open_demo.js


PS C:\git\node-pty\node-pty\demo>

C:\git\node-pty\node-pty\demo>showme
Der Befehl "showme" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

```


Sorry it is german output. In this case I typed ```showme```

**Comment by s-a** [comment]
In my file copy attempt I also missed the question output. ```do you want to overwrite (yes/no/all)```

**Comment by Tyriar** [comment]
Oh so you want to send data back to the terminal? Personally I use [xterm.js](https://github.com/sourcelair/xterm.js) which handles all keystroke handling, it needs access to a DOM though (electron). You can look at what `Terminal.evaluateEscapeSequences` does with a `KeyboardEvent` to deal with keystrokes (`result.key` gets sent to node-pty) https://github.com/sourcelair/xterm.js/blob/5bd803382a10b54b4b4dc51b95215c25bafa2abc/src/xterm.js#L1576

**Comment by s-a** [comment]
Yes `interactive shell coammands` is my topic here. This looks promising. Tried `xterm` many month ago with (as far I can remember) bad experience on windows. I see it depends on `node-pty` so I will give it a new try next week. It seems I missunderstood functionality of `node-pty`and I would say this issue is obsolete here. Do you have a PayPal account out there? I ' d like to donate you a :beer: for your nice support and hard work on open source repos.

**Comment by Tyriar** [comment]
Yes we recently got the xterm.js demo fixed on Windows via `node-pty` and using `gulp`.

Nope don't have anything setup, very nice of you to offer though. Get another :beer: for yourself :smile:
