### ISSUE TITLE
Add some proper API documentation

### ISSUE THREAD

**Issue by Tyriar** [Tyriar/node-pty#33]

**Comment by eddiewang** [comment]
is this forked from another project? trying to look for some helpful docs here.

**Comment by Tyriar** [comment]
There is much richer type information in 0.6.9:

![image](https://user-images.githubusercontent.com/2193314/28033318-b493c334-6562-11e7-8ee0-0bba9d458103.png)

**Comment by Tyriar** [comment]
Added typings now, the API surface got a lot smaller as I only added a handful of APIs. Will add more as people request them.

**Comment by raxod502** [comment]
Could this file be linked from the README? Or even better, could some actual HTML docs be generated? I was still under the impression that this project was undocumented until I found this issue, despite using the library several times.

**Comment by Tyriar** [comment]
@raxod502 good feedback, added an API section to the readme. HTML docs seem overkill imo.
