### ISSUE TITLE
Can't `pty.kill()` or `pty.destroy()` on Windows 10

### ISSUE THREAD

**Issue by matheuss** [Tyriar/node-pty#34]
Whenever I try to kill a pty process with `pty.kill()` or `pty.destroy()`, the whole parent process just crashes: 

![screen shot 2017-01-21 at 7 12 19 pm](https://cloud.githubusercontent.com/assets/4721750/22177968/77994b4c-e011-11e6-884b-f8b7c5d3bb6a.jpg)

The same happens inside Hyper:

<img width="386" alt="screen shot 2017-01-21 at 7 12 19 pm" src="https://cloud.githubusercontent.com/assets/4721750/22177970/805ca6d4-e011-11e6-96ab-d25384628662.png">

I wasn't able to get any relevant logs anywhere, not even on `Event Viewer`.

A `try-catch` is useless: 

```javascript
try {
  pty.kill();
} catch (err) {
  console.error(err);
}
```

The error never gets printed – the parent process just crashes.

If I `pty._close()`, everything works fine. I cannot reproduce this on macOS or Linux.

Any ideas? 😥

**Comment by Tyriar** [comment]
I'll have a look, winpty agent probably isn't being cleaned up properly.

**Comment by matheuss** [comment]
@Tyriar thank you ❤️ Do you think it's safe to ship Hyper with `pty._close()` on Windows?

**Comment by Tyriar** [comment]
I'd avoid shipping just yet as I'll look into this today/tomorrow. FYI I also published 0.6.1 which corrects the compiled JS to fix the Git Bash backspace issue so you can test with that in the meantime. https://github.com/Tyriar/node-pty/releases/tag/0.6.1

**Comment by matheuss** [comment]
Same issue on 0.6.1 😕 Will push `pty._close()` as a temporary workaround then. Thank you again!

**Comment by Tyriar** [comment]
Yep I can repro and have a test, working on fix now.

```js
    it("should not crash parent process", function(done) {
      const term = new WindowsTerminal('cmd.exe', [], {});
      term.kill();
      // Add done call to deferred function queue to ensure the kill call has completed
      term._defer(done);
    });
```

**Comment by matheuss** [comment]
Amazing @Tyriar ❤️ Any ETA for the release?

**Comment by Tyriar** [comment]
I'll probably release it later today, need to do some verification first.

**Comment by Tyriar** [comment]
@matheuss actually it would be ideal if you could also verify using `node-pty@0.6.2-beta1` 😄

**Comment by matheuss** [comment]
@Tyriar Perfect 💯 
<img width="315" alt="screen shot 2017-01-21 at 10 25 08 pm" src="https://cloud.githubusercontent.com/assets/4721750/22178797/83fd7cde-e028-11e6-9fa9-76dc1e16d6b6.png">

**Comment by Tyriar** [comment]
Published https://github.com/Tyriar/node-pty/releases/tag/0.6.2

**Comment by matheuss** [comment]
@Tyriar you're amazing ❤️

**Comment by LabhanshAgrawal** [comment]
@Tyriar the typings mention
https://github.com/microsoft/node-pty/blob/cd72d3303cb484e402381741e7e6a613886eda7b/typings/node-pty.d.ts#L179-L185
Is the type doc incorrect?

**Comment by LabhanshAgrawal** [comment]
Oops, sorry I misunderstood the `@throws` stuff, please ignore it.
