### ISSUE TITLE
Advise users who are using python = python3 to use the following

### ISSUE THREAD

**Issue by ioquatix** [Tyriar/node-pty#36]
apm config set python $(which python2.7)

Otherwise would run into this issue: https://github.com/nodejs/node-gyp/issues/1030

**Comment by Tyriar** [comment]
Thanks for letting me know. Due to you mentioning it will be fixed upstream soon and the error itself is fairly readable I think I'll leave this as is.

```
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
```

**Comment by ioquatix** [comment]
Just so you know, I actually don't have much confidence it will be fixed upstream soon, because to be honest, it's already been like 1.5 years :D

**Comment by Tyriar** [comment]
Haha, that's alright. I want to expand and clarify the build section eventually to call out all the dependencies needed to build winpty. I'll probably do that in https://github.com/Tyriar/node-pty/issues/25

**Comment by ioquatix** [comment]
The problem I have is that when `node-pty` is a dependency, it's hard for people to see these additional documentation or procedures. It would be great if it just works out of the box where possible.

**Comment by Tyriar** [comment]
The only way for it to work out of the box is to pre-compile the binaries for each architecture which I specifically wanted to avoid here as that involves checking in binaries (ew) and it can conflict with cause issues with some build systems.

**Comment by ioquatix** [comment]
I understand it has downsides, but it's not a bad solution overall, if it means that people who use the library don't have issues. The people who suffer the most are the people least able to compile it themselves.

**Comment by rash805115** [comment]
+1 to have an already compiled binary. My docker containers have increased in size after adding this library because I now have to include additional dependencies to make this project. The build time has also increased a little bit for this reason.
