### ISSUE TITLE
How to suppress input data from output listener

### ISSUE THREAD

**Issue by joeyzhao0113** [Tyriar/node-pty#38]
I see the all the input data got notified on the read listener method as below:

> ptyProcess.on('data', function(data) {
  console.log(data);   // this line will print 'ls' which is a input data
});

> ptyProcess.write('ls\r');

Is there a way to suppress the input data from output? And Is there a way to separate input and output?

**Comment by Tyriar** [comment]
When you send `ls` to the shell process it will send that back as it needs to be output to the screen. There is no way of forcing the behavior you're after AFAIK, you would need to see if `bash`/etc. is capable of suppressing the output.

One thing you may find useful is that you can launch commands as the shell process itself, telling node-pty to run `bash -c ls` will not output `ls` but will output the results.

**Comment by joeyzhao0113** [comment]
When I create a child process by nodejs `child_process.spawn` API, I can use `stdin` for input and `stdout` for output. In this way, I am able to separate input and output. Is there a way to use them in `node-pty`?

**Comment by Tyriar** [comment]
You cannot differentiate currently, not sure right now if it's possible or if  those details are lost when being run within a pty or not.

**Comment by joeyzhao0113** [comment]
Is this a limitation on pty? I can achieve that by creating a process through `child_process` directly. Is there any special consideration about PTY in this case?

**Comment by Tyriar** [comment]
But `ls` itself is output since the pty master (bash) needs to communicate that the user has entered `ls` to the pty slave (your program). If `ls` was not included in the output, terminals wouldn't really work?

```
Press `s`
  node-pty tells bash that s was pressed
    bash accepts s as input and modifies the terminal viewport
      bash gives node-pty back a set of output/escape sequences that apply the
      change, in this case just `s`
```
