### ISSUE TITLE
Is it possible fork an application with arguments?

### ISSUE THREAD

**Issue by sputnick** [Tyriar/node-pty#39]
I'm wondering if I can fork an app that responds with tty rather then bash? The use case would be for a terminal in web ui where the end user should not be able to exit into the top "bash".

**Comment by Tyriar** [comment]
You can pass in something like `sh -c ls` (cmd has an equivalent) which will exit once the command (`ls`) finishes, is this what you're after?

**Comment by sputnick** [comment]
Yeah thanks. It doesn't seem to work - don't get an error but looks like input/output isn't there.
I'll probably generated temp users to bind the process to instead of going this route if this doesn't work if that makes more sense. In essence I want to have one container serving multiple consoles but non of them should be able to "exit" up to the top "bash". Any other ideas would be great..

Just FYI when I kill the process started with 'sh -c "...."' I get the error:
Error: kill ESRCH

And on trying to fork a new one with the same params I get:
ioctl(2) failed

**Comment by Tyriar** [comment]
That's strange, that is how vscode launches multiple processes (in serial) that are all sent to the one terminal pane (well `bash -c <cmd>`). Nothing stopping multiple to run at once and all be displayed to the screen though?

**Comment by Tyriar** [comment]
Closing as this is definitely possible, you can see VS Code's usage in https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/terminal/electron-browser/terminalProcess.js
