### ISSUE TITLE
Windows build error: fatal error C1083: 'tracing/trace_event.h': No such file or directory 

### ISSUE THREAD

**Issue by luckcolors** [Tyriar/node-pty#44]
Hello.
I'm trying to npm install node-pty on windows 10 64 bit.
On my system i have installed: Nodejs 7.7.0, python27, Visualstudio 2015 Community.
I get the following build error.

```
  win_delay_load_hook.cc
C:\Users\luckcolors\.node-gyp\7.7.0\include\node\node.h(44): fatal error C1083: Non è possibile aprire il file inclusione: 'tracing/trace_event.h': No such file or di
rectory (compilazione del file di origine ..\src\win\pty.cc) [C:\Users\luckcolors\Desktop\black-screen\node_modules\node-pty\build\pty.vcxproj]
```
I hope you can help me. :)

**Comment by luckcolors** [comment]
I tried building node-pty again with nodejs 7.4.0 and the build now succeeds. Probably that header file has been removed in the newer version of nodejs.

**Comment by Tyriar** [comment]
Good to know :smiley: I've only testing it up to node 6.x.

**Comment by luckcolors** [comment]
Closing for now, feel free to reopen if you need.
