### ISSUE TITLE
Wrong pid on windows: Error: kill ESRCH

### ISSUE THREAD

**Issue by coderaiser** [Tyriar/node-pty#45]
Every new started process gets wrong pid which is different from ones shown in `task manager`.
Could be reproduced with the [demo of xterm.js](https://github.com/sourcelair/xterm.js/tree/bebe43e5e108b081a8ead57b881e7ea1504164d7/demo).
Related to [xterm.js issue](https://github.com/sourcelair/xterm.js/pull/584).

```sh
> xterm@2.3.2 start C:\Users\coderaiser\Documents\GitHub\xterm.js
> node demo/app

App listening to http://127.0.0.1:3000
Created terminal with PID: 928
Connected to terminal 928
internal/process.js:173
      throw errnoException(err, 'kill');
      ^

Error: kill ESRCH
    at exports._errnoException (util.js:1022:11)
    at process.kill (internal/process.js:173:13)
    at WebSocket.<anonymous> (C:\Users\coderaiser\Documents\GitHub\xterm.js\demo\app.js:72:13)
    at emitTwo (events.js:111:20)
    at WebSocket.emit (events.js:191:7)
    at WebSocket.cleanupWebsocketResources (C:\Users\coderaiser\Documents\GitHub\xterm.js\node_modules\ws\lib\WebSocket.js:950:8)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1281:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v7.2.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! xterm@2.3.2 start: `node demo/app`
npm ERR! Exit status 1
```

**Comment by Tyriar** [comment]
This is also probably the root cause of https://github.com/Microsoft/vscode/issues/14286

It's related to winpty, currently it's being set to `(int)winpty_agent_process(pc)` [here](https://github.com/Tyriar/node-pty/blob/864ec619fd39c3b18679a410591717416b7ea07e/src/win/pty.cc#L249), which points at the [winpty agent process](https://github.com/Tyriar/node-pty/blob/f0a3e9816124ec9672756a5357d8d06e65d218de/deps/winpty/src/libwinpty/winpty.cc#L693).

**Comment by Tyriar** [comment]
@rprichard is there an easy way to get the winpty agent process ID from `winpty_agent_process`? I see it being set [here](https://github.com/Tyriar/node-pty/blob/f0a3e9816124ec9672756a5357d8d06e65d218de/deps/winpty/src/libwinpty/winpty.cc#L519) but not sure if this is surfaced through the API?

**Comment by rprichard** [comment]
Yes, you'd call `GetProcessId` on the `winpty_agent_process` handle.  Don't close the agent process handle afterwards -- libwinpty does that itself.

Do you want the PID of the winpty agent or the PID of the process running inside winpty (e.g. `powershell.exe`)?  If you want the latter, then you need to get a process handle from `winpty_spawn` and pass that to `GetProcessId`.

The code is currently getting the spawned child process' handle and putting it into `handle`:
```
HANDLE handle = nullptr;
BOOL spawnSuccess = winpty_spawn(pc, config, &handle, nullptr, nullptr, nullptr);
```
The code doesn't do anything with `handle`, though.  It doesn't even close the handle, so the handle is leaked (until the node process exits).  (The PID is *also* leaked and can't be reused until the node process exits).

I'd guess you actually want to use `GetProcessId(handle)`, then call `CloseHandle` on the spawned handle when the pty object is cleaned up.

Alternatively, if you really do want the agent PID, then you can fix the handle leak by passing nullptr to winpty_spawn:
```
BOOL spawnSuccess = winpty_spawn(pc, config, nullptr, nullptr, nullptr, nullptr);
```

**Comment by Tyriar** [comment]
Thanks @rprichard, I do want the inner process from `winpty_spawn` (powershell).

**Comment by Tyriar** [comment]
Managed to get this working pretty easily thanks to your help @rprichard 👍 

![image](https://cloud.githubusercontent.com/assets/2193314/23835912/cad5a642-072c-11e7-893f-2f0190b17863.png)
