### ISSUE TITLE
Handling errors

### ISSUE THREAD

**Issue by pablopunk** [Tyriar/node-pty#74]
What is the best way to handle errors? For example if I got the following code:
```javascript
var pty = require('node-pty');
var shell = 'wrongshell'
var ptyProcess = pty.spawn(shell, [], options);

ptyProcess.on('data', function(data) {
  console.log(data);
});
```

The line `console.log(data)` is gonna print `execvp(3) failed.: No such file or directory` because the shell `wrongshell` doesn't exist.

Is it better to check if the shell exists before initializing pty? Or is there any error handling built in to handle this type of errors?

**Comment by Tyriar** [comment]
I guess it's up to you and your application, you may have difficulty checking whether `wrongshell` exists though as you'll need to check the $PATH (and also source .bashrc/.zshrc etc. as appropriate). 

For VS Code we just output it in the panel but then immediately close the panel and show the exit code of the shell process. It's a pretty bad experience right now but it's better than doing nothing.

**Comment by pablopunk** [comment]
@Tyriar yeah actually I needed this to resolve [this issue](https://github.com/zeit/hyper/issues/1589), cause right now the window is just being closed without any notice. I guess the best will be displaying a warning or something like that.

**Comment by Tyriar** [comment]
Very similar to the VS Code problem, right now I listen to see if the terminal exits within 500ms of launching and if so, I assume it crashed due to the config. Not perfect but a good stop gap solution until something better is implemented.
