### ISSUE TITLE
Provide exit code on exit event in Windows

### ISSUE THREAD

**Issue by zrisher** [Tyriar/node-pty#75]
Hello! I'm having trouble retrieving the exit code from my process when running node-pty on Windows. 

The [unix terminal](https://github.com/Tyriar/node-pty/blob/master/src/unixTerminal.ts) emits an exit event containing the code:
```
this.emit('exit', code, signal);
```

but the [windows terminal](https://github.com/Tyriar/node-pty/blob/master/src/windowsTerminal.ts) simply returns null with that event:
```
this.emit('exit', null);
``` 

Any pointers on how I might implement?

**Comment by zrisher** [comment]
For my case, I found I can simply `echo $lastexitcode` and then parse the result of that from the returned data. 

It is possible to provide this to the end of my process, though, using `exit $lastexitcode`. I believe unix does this automatically, which is perhaps why the exit code isn't available via the exit event on the Windows terminal?

**Comment by Tyriar** [comment]
Hi @rprichard, is it possible to get the process exit code from winpty?

**Comment by rprichard** [comment]
Yes, after the process has exited, call `GetExitCodeProcess` on the process' handle.

**Comment by Tyriar** [comment]
Thanks @rprichard :smiley:

**Comment by stevenvachon** [comment]
Running into this as well. This one's pretty critical.
