### ISSUE TITLE
cwd is ignored when spawning using sudo su - user_name

### ISSUE THREAD

**Issue by PradeepJaiswar** [Tyriar/node-pty#84]
Can anyone guide why cwd option is ignored when I user `sudo su - username` while spawning the process. It takes me to `/home/user_name` no matter what I pass in cwd

```
  var term = pty.spawn('sudo', ['su','-',user_name], {
          name: 'xterm-color',
          cwd: /path/to/other/directory,
          env: process.env
        });
```

**Comment by jrop** [comment]
I believe the single dash `-` in `sudo su - username` clears the current environment.

In order to keep CWD, you may need to follow [other methods](https://serverfault.com/questions/27317/linux-use-su-but-keep-the-current-directory)

**Comment by Tyriar** [comment]
Thanks @jrop, closing this off.

**Comment by PradeepJaiswar** [comment]
If anyone facing the same issue. This can be also solved by just updating the `~/.bashrc`

Putting below two line in `~/.bashrc` file worked for me
```
PROMPT_COMMAND+='printf %s "$PWD" > ~/.storepwd'
[ -s ~/.lastdirectory ] && cd `cat ~/.lastdirectory`
```

Ref https://stackoverflow.com/questions/767040/save-last-working-directory-on-bash-logout
