### ISSUE TITLE
Title update event

### ISSUE THREAD

**Issue by Luke123443** [Tyriar/node-pty#88]
I struggled to find any documentation or code in other projects that would link me to the correct event name, and I had to open this issue. So, long story short, the question is: Which event should I listen to in order to get the pty title?

I saw Microsoft using `process.on('message')`, but they're forking the pty from a file. What if I just spawn the pty? What is the event called?

**Comment by Tyriar** [comment]
You can grab the name of the process using `pty.process` as in here https://github.com/Microsoft/vscode/blob/2af6c114c3a48fd06e86683260483780727ffd0b/src/vs/workbench/parts/terminal/node/terminalProcess.ts#L142

There is no event right now so VS Code polls this property to update the process title.

**Comment by Luke123443** [comment]
Ohh thank you. I checked out the same file before opening this issue but i couldn't find what i was looking for. Thank you man, you saved my day.

**Comment by Tyriar** [comment]
No worries 😃
