### ISSUE TITLE
Precompiled bin

### ISSUE THREAD

**Issue by igor-lemon** [Tyriar/node-pty#89]
Hi. Add please precompiled binaries for simple init cross-platform apps.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Tyriar/node-pty/issues/46

**Comment by igor-lemon** [comment]
@Tyriar I think that you don't understand me. I mean precompiled node binaries with node-pre-gyp.
Like as
https://github.com/EmergingTechnologyAdvisors/node-serialport/releases

**Comment by Tyriar** [comment]
@igor-lemon that's the problem https://github.com/Tyriar/node-pty/issues/46 is trying to solve, with the first step being to remove the winpty compile step as that's the most costly.
