### ISSUE TITLE
Error during script-runner package for Atom editor

### ISSUE THREAD

**Issue by liganega** [Tyriar/node-pty#90]
I am using OSX Sierra 10.12.5

When I try to install scrip-runner package for the atom edition, the following installation error pops up. 
The error message hints at a possible relation to node-pty.

It's however very strange because the package installation on another mac machine with OSX Sierra goes without any problem.

Any help would be appreciated.

=====

Installing “script-runner@2.1.1” failed.Hide output…

node-pty@0.6.6 install /private/var/folders/qx/4wjlwgbd2497fnjdgf1xzxrc0000gn/T/apm-install-dir-117512-7325-1d2ov0r.zcmynfjemi/node_modules/script-runner/node_modules/node-pty
node scripts/install.js
/private/var/folders/qx/4wjlwgbd2497fnjdgf1xzxrc0000gn/T/apm-install-dir-117512-7325-1d2ov0r.zcmynfjemi
└── (empty)

gyp ERR! configure error
gyp ERR! stack Error: Python executable "/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh" is v3.5.1, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack at failPythonVersion (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:454:14)
gyp ERR! stack at /Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:443:9
gyp ERR! stack at ChildProcess.exithandler (child_process.js:197:7)
gyp ERR! stack at emitTwo (events.js:106:13)
gyp ERR! stack at ChildProcess.emit (events.js:191:7)
gyp ERR! stack at maybeClose (internal/child_process.js:877:16)
gyp ERR! stack at Socket. (internal/child_process.js:334:11)
gyp ERR! stack at emitOne (events.js:96:13)
gyp ERR! stack at Socket.emit (events.js:188:7)
gyp ERR! stack at Pipe._handle.close [as _onclose] (net.js:498:12)
gyp ERR! System Darwin 16.6.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /private/var/folders/qx/4wjlwgbd2497fnjdgf1xzxrc0000gn/T/apm-install-dir-117512-7325-1d2ov0r.zcmynfjemi/node_modules/script-runner/node_modules/node-pty
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/qx/4wjlwgbd2497fnjdgf1xzxrc0000gn/T/apm-install-dir-117512-7325-1d2ov0r.zcmynfjemi/package.json'
npm WARN apm-install-dir-117512-7325-1d2ov0r.zcmynfjemi No description
npm WARN apm-install-dir-117512-7325-1d2ov0r.zcmynfjemi No repository field.
npm WARN apm-install-dir-117512-7325-1d2ov0r.zcmynfjemi No README data
npm WARN apm-install-dir-117512-7325-1d2ov0r.zcmynfjemi No license field.
npm ERR! Darwin 16.6.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/gslee/.atom/.apm/.apmrc" "--userconfig" "/Users/gslee/.atom/.apmrc" "install" "/private/var/folders/qx/4wjlwgbd2497fnjdgf1xzxrc0000gn/T/d-117512-7325-hpcdfg.8mll7n9udi/package.tgz" "--runtime=electron" "--target=1.3.15" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! node-pty@0.6.6 install: node scripts/install.js
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-pty@0.6.6 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-pty package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs node-pty
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! npm owner ls node-pty
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! /private/var/folders/qx/4wjlwgbd2497fnjdgf1xzxrc0000gn/T/apm-install-dir-117512-7325-1d2ov0r.zcmynfjemi/npm-debug.log
npm ERR! code 1

**Comment by Tyriar** [comment]
```
gyp ERR! configure error
gyp ERR! stack Error: Python executable "/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh" is v3.5.1, which is not supported by gyp.
```

This is an issue with gyp and the version of Python you have installed.

**Comment by liganega** [comment]
You are right. The python command was linked to python3, not python2.

Thank you.
