### ISSUE TITLE
Race condition between the forked program output and 'data' event ?

### ISSUE THREAD

**Issue by hexa00** [Tyriar/node-pty#99]
I would like to make sure that I get all the data that the forked program outputs from the start.

But looking at https://github.com/Tyriar/node-pty/blob/master/src/unixTerminal.ts in the constructor:
``` typescript
    this.socket = new PipeSocket(term.fd);
    if (encoding !== null) {
      this.socket.setEncoding(encoding);
    }
this.socket.resume();
```

The resume here makes it such that if I do:

``` typescript
const term = pty.spawn...
term.on('data', data => something);
```
I can't be sure that a data event has not fired between those 2 lines...

I also notice that there's a `pause` function on the terminal but I can't call that before the constructor, I also can't setup the data event handler before the constructor...

Is there a reason for this .resume() call  ?

**Comment by Tyriar** [comment]
@hexa00 have you run into a problem with this? The VS Code terminal has been running on this code for 12 months now and no reports for this (there was on similar initial data missing bug but that was due to the terminal not being in the DOM). Are we talking an edge case on an really slow machine or something?

The call itself has been there since before I forked the library. It looks like upstream did made a change adding an option for this https://github.com/chjj/pty.js/commit/ef6aa14981686daf869c0c05af326f84140fa97c.

**Comment by hexa00** [comment]
The problem is that in the project I'm working on, the creation of the terminal with pty.spawn happens at a different time than the registration of the data callback.  

So it was very apparent I would miss a lot of information since the data callback was registered maybe 1 sec after the pty.spawn call.

I've worked around it for now by using promises to register the data callaback even if some other ressource I need is not ready.

However the fix you've pointed to from upstream would be great. As it would allow me to remove that workaround and it would fix any possible issues that may happen even when you register the data callback asap. WDTY?

**Comment by Tyriar** [comment]
@hexa00 to clarify, if I pulled in the change with the option does that mean that you would need to call [`pty.resume()`](https://github.com/Tyriar/node-pty/blob/085f1b180f7cfbb66e6656dd8dc95dbde685351f/src/terminal.ts#L72) manually?

**Comment by hexa00** [comment]
No by default things would not change from the current behavior.

With the resume option to false however you would have to add a data handler, a pipe or call resume see: https://nodejs.org/api/stream.html#stream_readable_streams  Section about Two modes

But that's what most people will do anyway.

**Comment by Tyriar** [comment]
Ah I see. If things are the same, maybe this should just be the default and not worry about the additional option, people can just call `pty.resume()` if they need to?

**Comment by hexa00** [comment]
Yes I think it would be better with the default without a resume call in node-pty and the caller will most likely call pty.on('data', something) and this will resume the stream automatically.

**Comment by Tyriar** [comment]
Cool, sounds like a plan. This behavior was always the intent so I'll include this in a patch release.

**Comment by hexa00** [comment]
Great! Thank you very much :)

**Comment by Tyriar** [comment]
@hexa00 please review :smile: https://github.com/Tyriar/node-pty/commit/90e0c70e6502398e8bd13195a2b1b87a0305e4c9
